version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: othello_mysql
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # ルートユーザーのパスワード
      MYSQL_DATABASE: othello_db         # 自動で作成されるデータベース名
      MYSQL_USER: othello_user           # カスタムユーザー名
      MYSQL_PASSWORD: userpassword       # カスタムユーザーのパスワード
    volumes:
      - db_data:/var/lib/mysql           # データの永続化用ボリューム

volumes:
  db_data:
