version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: othello_mysql
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: othello_db
      MYSQL_USER: othello_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: othello_backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: othello_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
